### PR TITLE
Api

### PR DESCRIPTION
**Pull request by HawiCaesar**
Merge a simple working version of API to develop

### CODE REVIEW

**Comment by HawiCaesar** [comment]
I want to remove forms.py from the api to remove code duplication stated by CodeClimate

**Comment by drizzentic** [comment]
Hey @HawiCaesar , the commits are quite many and it makes is hard for someone to do a review. Kindly try to make you branches have fewer commits.

**Comment by HawiCaesar** [comment]
@drizzentic Thanks for the comment. I realised I was trying out different implementation and forgot to commit when an implementation worked.

**Comment by drizzentic** [comment]
I realize you have merged. But kindly checkout my comment on the code. @HawiCaesar

**Pull request merged**
